---
- an abandoned mining colony
- the embattled edge of Fong-Chandra space
- the ruins of Old Earth
- the New Fleet's vast shipyard
- the smoking ruin of Kali 7
- the scout-world of Bright Eye
- the bubbling cauldron of X-Ray Bay